### ISSUE TITLE
"save -p -" still doesn't output anything

### ISSUE THREAD

**Issue by mirkojovanovic** [cmus/cmus#954]
I have found this old issue https://github.com/cmus/cmus/issues/784 that should be solved, but I still have the same problem. The command doesn't output anything. Similar commands with `-l`, `-q` and `-L` output as expected from reading the manpage. Hope this will be fixed soon, thanks! 

---

1) `uname -a`:
```
Linux toshiba 5.5.2-arch1-1 #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

**Comment by nefthy** [comment]
This issue was fixed, after the 2.8.0 release. Since there has not been any release since you will have to compile from source, if you need this fix.

**Comment by mirkojovanovic** [comment]
Thanks! Should `-p` work with `-e`? Doesn't output metadata :(

**Comment by karstengo** [comment]
> 

I downloaded and compiled the repo. Still it does not saves the playlist view with cmus-remote ... e.g. 4 for me.
When I manually enter 

```
:save my.txt
```

It works.

What is strange thought when I show the version

```
17:05  ~  🐧  /usr/local/bin/cmus --version
cmus v2.10.0-8-gdc2752c
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

in cmus itsel it still shows the "2.8.x" in header bar. Is there a caching issue?
